version: '3.8'

services:

   app :
      build: .
      volumes:
        - .:/app #direct link to the container
      ports:
          - 8000:8000
      #name image
      image: dev:app
      container_name: dev-app
      command: python manage.py runserver 0.0.0.0:8000

      env_file:
        - .env


   celery:
      build: .
      container_name: dev-celery
      command: celery -A tech_mentorship_platform worker --loglevel=info
      volumes:
        - .:/app
      env_file:
        - .env
      depends_on:
        - app

   celery-beat:
      build: .
      container_name: dev-celery-beat
      command: celery -A tech_mentorship_platform beat --loglevel=info
      volumes:
        - .:/app
      env_file:
        - .env
      depends_on:
        - app