# Generated by Django 5.1.7 on 2025-04-09 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentorship', '0002_alter_mentorship_unique_together_availableslot_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentee',
            name='goals',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='mentee',
            name='interest',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='mentor',
            name='bio',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='mentor',
            name='skills',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='session',
            name='note',
            field=models.TextField(blank=True, default=''),
        ),
    ]
