# Generated by Django 5.1.7 on 2025-04-10 22:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentorship', '0003_alter_mentee_goals_alter_mentee_interest_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AvailableSlot',
            new_name='BookingSlot',
        ),
        migrations.AlterField(
            model_name='mentorship',
            name='mentee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentorship', to='mentorship.mentee'),
        ),
        migrations.AlterUniqueTogether(
            name='bookingslot',
            unique_together={('mentor', 'start_time')},
        ),
    ]
