name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.13'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Run tests
      run: |
        pytest --reuse-db

#  docker-build-and-push:
#    needs: build-and-test
#    runs-on: ubuntu-latest
#    env:
#      docker_image: showq10/tech-mentorship-platform
#      docker_pass: ${{ secrets.DOCKER_PASSWORD }}
#      docker_username: ${{ secrets.DOCKER_USERNAME }}
#
#    steps:
#    - name: Checkout code
#      uses: actions/checkout@v3
#
#    - name: Log in to Docker Hub
#      env:
#      run: echo "$docker_pass" | docker login -u "$docker_username"  --password-stdin
#
#    - name: Build Docker image
#      run: docker build -t "$docker_image" .
#
#    - name: Push Docker image
#      run: docker push "$docker_image"
#
#  deploy-to-render:
#    needs: docker-build-and-push
#    runs-on: ubuntu-latest
#
#    steps:
#      - name: Trigger Render Deploy Hook
#        env:
#          deploy_url: ${{ secrets.RENDER_DEPLOY_HOOK_URL }}
#        run: curl -X POST "$deploy_url"